spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/orderdb
#    username: postgres
#    password: postgres
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

logging:
  level:
    com.example.orderapi: INFO
    org.hibernate.SQL: DEBUG
